[book]
authors = ["Govind Reddy"]
language = "en"
multilingual = false
src = "manuscript"
title = "The Self-Emergent Universe"

[output.html]
git-repository-url = "https://github.com/gtreddy/the-self-emergent-universe"
